image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

food-build:
  stage: build
  script:
    gradle :foodservices:assemble

food-PMD-checkStyle:
  stage: staticAnalysis
  script:
    gradle :foodservices:checkstyleMain :foodservices:checkStyleTest :foodservices:pmdMain :foodservices:pmdTest
  allow_failure: true

food-test:
  stage: test
  script:
    gradle --info :foodservices:test
