image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

house-build:
  stage: build
  script:
    gradle :housemanagement:assemble

house-PMD-checkStyle:
  stage: staticAnalysis
  script:
    gradle :housemanagement:checkstyleMain :housemanagement:checkStyleTest :housemanagement:pmdMain :housemanagement:pmdTest
  allow_failure: true

house-test:
  stage: test
  script:
    gradle --info :housemanagement:test
